config/routes.rb
Scoreboard::Application.routes.draw do

  match "my_scores" => "scores#my_scores"

  get "user_sessions/new"


  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :scores
  resources :users, :only => [:new, :create, :update, :edit, :show]

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  namespace :admin do
    resources :scores
    resources :users
    resources :roles
    resources :achievements
    resources :achievement_categories
    root :to => 'admin#index'
  end
 
  root :to => 'play#index'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :num_to_complete
  validates_presence_of :achievement_category

  belongs_to :achievement_category

  def return_progress(progress)
    if progress < num_to_complete
      "#{progress} / #{num_to_complete}"
    else
      "#{num_to_complete} / #{num_to_complete}"
    end
  end

  def return_complete(progress)
    if progress.to_i < num_to_complete.to_i
      '<i class="icon-remove"></i>'
    else
      '<i class="icon-ok"></i>'
    end
  end

  def return_complete?(progress)
    if progress.to_i < num_to_complete.to_i
      false
    else
      true
    end
  end
end

app/controllers/admin/achievements_controller.rb
class Admin::AchievementsController < ApplicationController
  # GET /achievements
  # GET /achievements.json
  def index
    @achievements = Achievement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @achievements }
    end
  end

  # GET /achievements/1
  # GET /achievements/1.json
  def show
    @achievement = Achievement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @achievement }
    end
  end

  # GET /achievements/new
  # GET /achievements/new.json
  def new
    @achievement = Achievement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @achievement }
    end
  end

  # GET /achievements/1/edit
  def edit
    @achievement = Achievement.find(params[:id])
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(params[:achievement])

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to admin_achievements_path, notice: 'Achievement was successfully created.' }
        format.json { render json: @achievement, status: :created, location: @achievement }
      else
        format.html { render action: "new" }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /achievements/1
  # PUT /achievements/1.json
  def update
    @achievement = Achievement.find(params[:id])

    respond_to do |format|
      if @achievement.update_attributes(params[:achievement])
        format.html { redirect_to admin_achievements_url, notice: 'Achievement was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement = Achievement.find(params[:id])
    @achievement.destroy

    respond_to do |format|
      format.html { redirect_to admin_achievements_url }
      format.json { head :ok }
    end
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/views/admin/achievements/edit.html.haml
%fieldset
  %legend
    Edit Achievement
  %br/

= form_for @achievement, :url => admin_achievement_path, :html => {:class => 'form-horizontal'} do |f|
  -if @achievement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@achievement.errors.count, "error")} prohibited this achievement from being saved:"
      %ul
        - @achievement.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :num_to_complete, :class => 'control-label'
    .controls
      = f.number_field :num_to_complete, :class => 'text_field'
  .control-group
    = f.label :achievement_category, :class => 'control-label'
    .controls
      = select(:achievement_category, :achievement_category_id, AchievementCategory.all.collect {|r| [r.name, r.id]}, {:prompt => 'Select Category'})
  .form-actions
    = f.submit 'Save Achievement', :class => 'btn btn-primary'
    = link_to 'Cancel', admin_achievements_url, :class => 'btn'

app/views/admin/achievements/index.html.haml
%h1 Listing achievements

%table.table.table-striped
  %tr
    %th Name
    %th Num to complete
    %th Achievement category
    %th
    %th
    %th

    - AchievementCategory.all.each do |achievement_category|
      %tr
        %td
          %strong=achievement_category
        %td
        %td
      - achievement_category.achievements.each do |achievement|     
        %tr{:class => cycle('list_line_odd', 'list_line_even')}
          %td= achievement.name
          %td= achievement.num_to_complete
          %td

%br

= link_to 'New Achievement', new_admin_achievement_path

app/views/admin/achievements/new.html.haml
%fieldset
  %legend
    New Achievement
  %br/
= form_for @achievement, :url => admin_achievements_path, :html => {:class => 'form-horizontal'} do |f|
  -if @achievement.errors.any?
    .alert.alert-error
      #error_explanation
        %h2= "#{pluralize(@achievement.errors.count, "error")} prohibited this achievement from being saved:"
        %ul
          - @achievement.errors.full_messages.each do |msg|
            %li= msg

  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :num_to_complete, :class => 'control-label'
    .controls
      = f.number_field :num_to_complete, :class => 'text_field'
  .control-group
    = f.label :achievement_category, :class => 'control-label'
    .controls
      = select(:achievement, :achievement_category_id, AchievementCategory.all.collect {|r| [r.name, r.id]}, {:prompt => 'Select Category'})
  .form-actions
    = f.submit 'Create Achievement', :class => 'btn btn-primary'
    = link_to 'Cancel', admin_achievements_url, :class => 'btn'

app/views/admin/achievements/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @achievement.name
%p
  %b Num to complete:
  = @achievement.num_to_complete
%p
  %b Achievement category:
  = @achievement.achievement_category_id

= link_to 'Edit', edit_achievement_path(@achievement)
\|
= link_to 'Back', achievements_path