config/routes.rb
Scoreboard::Application.routes.draw do

  match "my_scores" => "scores#my_scores"

  get "user_sessions/new"


  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :scores
  resources :users, :only => [:new, :create, :update, :edit, :show]

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  namespace :admin do
    resources :scores
    resources :users
    resources :roles
    resources :achievements
    resources :achievement_categories
    root :to => 'admin#index'
  end
 
  root :to => 'play#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  validates_length_of :name, :minimum => 1
  validates_uniqueness_of :name
  def to_s
    name
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to admin_roles_url, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to admin_roles_url, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to admin_roles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/admin/roles/_form.html.haml
= form_for(@role, :url => admin_roles_path, :html => {:class => 'form-horizontal'}) do |f|
  - if @role.errors.any?
    .alert.alert-error
      %h2
        = pluralize(@role.errors.count, "error")
        prohibited this author from being saved:
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'

  .form-actions
    = f.submit 'Create Role', :class => 'btn btn-primary'
    = link_to 'Cancel', admin_roles_url, :class => 'btn'

app/views/admin/roles/edit.html.haml
= form_for(@role, :url => admin_role_path(@role), :html => { :class => "edit_user form-horizontal"}) do |f|
  - if @role.errors.any?
    .alert.alert-error
      %h2
        = pluralize(@role.errors.count, "error")
        prohibited this author from being saved:
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    %legend
      Edit Role
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name
    .content-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, :rows => 4

    .form-actions
      = f.submit nil, :class => 'btn btn-primary'

app/views/admin/roles/index.html.haml
%h3 Roles
%table.table.table-striped
	%thead
		%tr
			%th Name
			%th Number of Users
			%th Description
	%tfoot
		%tr
			%td
				= pluralize(@roles.count, 'role')
			%td
			%td
		%tbody
		- @roles.each do |role|
			%tr{:class => cycle('list_line_odd', 'list_line_even')}
				%td= link_to role.name, edit_admin_role_path(role)
				%td= role.users.count
				%td= role.description
%p
	= link_to "Add Role", new_admin_role_path

app/views/admin/roles/new.html.haml
%fieldset
  %legend
    New Role
  %br/
= render 'form'

app/views/admin/roles/show.html.haml
%p
	= @role.name