config/routes.rb
Scoreboard::Application.routes.draw do

  match "my_scores" => "scores#my_scores"

  get "user_sessions/new"


  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :scores
  resources :users, :only => [:new, :create, :update, :edit, :show]

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  namespace :admin do
    resources :scores
    resources :users
    resources :roles
    resources :achievements
    resources :achievement_categories
    root :to => 'admin#index'
  end
 
  root :to => 'play#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :scores
  belongs_to :role

  has_attached_file :photo, 
                  :styles => { :medium => "160x120>", :small => "100x100>"},
                  :default_url => 'http://placehold.it/160x120'

  def calc_level
    (points.to_i/10000).floor+1
  end

  #POINTS
  def points_til_next_level
    10000-current_level_points
  end

  def current_level_points
    points.to_i-(calc_level-1)*10000
  end

  def level_points_percent
    current_level_points/10000.0*100
  end

  #EGGS
  def eggs_in_dozen
    eggs.to_i%12
  end

  def eggs_in_dozen_percent
    eggs_in_dozen/12.0*100
  end

  def dozens_of_eggs
    (eggs/12).floor
  end

  #achievements
  def achievement_progress(achievement)
    #check which category an achievement is so we can pass in the correct instance variable
    if achievement.achievement_category == AchievementCategory.find_by_name('Words Solved')
      achievement.return_progress(words_solved)
    elsif achievement.achievement_category == AchievementCategory.find_by_name('Points All Time')
      achievement.return_progress(points)
    else
      achievement.return_progress(self.scores.maximum("level"))
    end
  end

  def achievement_completed(achievement)
    if achievement.achievement_category == AchievementCategory.find_by_name('Words Solved')
      achievement.return_complete(words_solved)
    elsif achievement.achievement_category == AchievementCategory.find_by_name('Points All Time')
      achievement.return_complete(points)
    else
      achievement.return_complete(self.scores.maximum("level"))
    end
  end

  def achievement_completed?(achievement)
    if achievement.achievement_category == AchievementCategory.find_by_name('Words Solved')
      achievement.return_complete?(words_solved)
    elsif achievement.achievement_category == AchievementCategory.find_by_name('Points All Time')
      achievement.return_complete?(points)
    else
      achievement.return_complete?(self.scores.maximum("level"))
    end
  end




  def role_symbols
    if role
      [role.name.downcase.to_sym]
    else
      [:guest]
    end
  end

  def to_s
    username
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new  
    @user = User.new  
  end 

  def show
     @user = User.find(params[:id])
  end 
    
  def create  
    @user = User.new(params[:user])  
    if @user.save  
      flash[:notice] = "New user successfully created"  
      redirect_to admin_users_url  
    else  
      render :action => 'new'  
    end  
  end  

  def edit  
    @user = User.find(params[:id]) 
  end  
    
  def update  
    @user = User.find(params[:id])  
    if @user.update_attributes(params[:user])  
      flash[:notice] = "Successfully updated user."  
      redirect_to admin_users_url  
    else  
      render :action => 'edit'  
    end  
  end 

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new  
      @user = User.new  
  end  
    
  def show
    @achievements = Achievement.all(:order => 'achievement_category_id')
  end

  def create  
    @user = User.new(params[:user])  
    if @user.save  
      flash[:notice] = "Registration successful."  
      redirect_to root_url  
    else  
      render :action => 'new'  
    end  
  end  

  def edit  
    @user = current_user  
  end  
    
  def update  
    @user = current_user  
    if @user.update_attributes(params[:user])  
      #flash[:notice] = "Successfully updated profile."  
      redirect_to user_path(current_user)  
    else  
      render :action => 'edit'  
    end  
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for @user, :url => admin_users_url, :html => { :class => 'form-horizontal' } do |f|
  - if @user.errors.any?
    .alert.alert-error
      %h2
        = pluralize(@user.errors.count, "error")
        on this form:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :username, :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :class => 'text_field'

  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'text_field'
  .control-group
    = f.label :role, :class => 'control-label'
    .controls
      = select(:user, :role_id, Role.all.collect {|r| [r.name, r.id]}, {:prompt => 'Select Role'})

  .form-actions
    = f.submit 'Create User', :class => 'btn btn-primary'
    = link_to 'Cancel', admin_users_url, :class => 'btn'

app/views/admin/users/edit.html.haml
%h2 Edit Info
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:role)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tfoot
    %tr
      %td
        = pluralize(@users.count, 'user')
      %td
      %td
      %td
      %td
      %td
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, admin_user_path(user)
        %td= user.username
        %td= user.email
        %td= user.role
        %td=l user.created_at.localtime
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_user_url, :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
%fieldset
  %legend
    New User
  %br/
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = @user.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:role) + ':'
  %br
  = @user.role


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'