config/routes.rb
Scoreboard::Application.routes.draw do

  match "my_scores" => "scores#my_scores"

  get "user_sessions/new"


  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :scores
  resources :users, :only => [:new, :create, :update, :edit, :show]

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"

  namespace :admin do
    resources :scores
    resources :users
    resources :roles
    resources :achievements
    resources :achievement_categories
    root :to => 'admin#index'
  end
 
  root :to => 'play#index'

end

app/views/layouts/_navbar.html.haml
.navbar
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Word Bird', root_url, :class => 'brand'
      .container.nav-collapse
        %ul.nav
          %li= link_to "Leader Board", scores_url
          %li= link_to "Help", '/help.html'
        -if current_user
          %ul.nav.pull-right
            %li= link_to 'Welcome, '+current_user.to_s, user_path(current_user)
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                My Stuff
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Edit Info", edit_user_path(current_user)
                %li= link_to "My Scores", my_scores_url
                /%li= link_to "Achievements", "#"
                %li.divider
                %li= link_to "Logout", logout_path
        -else
          %ul.nav.pull-right
            %li= link_to 'Login', login_path
            %li.divider-vertical
            %li= link_to 'Register', new_user_path

app/views/layouts/_navbar_admin.html.haml
.navbar
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Word Bird', root_url, :class => 'brand'
      .container.nav-collapse
        %ul.nav
          %li= link_to "Leader Board", scores_url
          %li= link_to "My Scores", my_scores_url
          
        %ul.nav.pull-right
          %li= link_to 'Welcome, '+current_user.to_s, user_path(current_user)
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Admin
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Roles", admin_roles_url
              %li= link_to "Users", admin_users_url
              %li.divider
              %li= link_to "Achievement Categories", admin_achievement_categories_url
              %li= link_to "Achievements", admin_achievements_url
              %li.divider
              %li= link_to "Edit Info", edit_user_path(current_user)
              %li.divider
              %li= link_to "Logout", logout_path

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Word Bird Admin"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "game"
    = csrf_meta_tags
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}/
    /%script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"}


    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .main_content
      = render 'layouts/navbar_admin'
      .outer
        - flash.each do |key, msg|
          = content_tag :div, msg, :class => [key, " message"], :class => "alert alert-#{key}"
        = yield
          

        
    
      %footer
        %p &copy; Word Bird 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"}
    = javascript_include_tag "game"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Word Bird"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "game"
    = csrf_meta_tags
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}/
    /%script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"}


    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .main_content
      = render 'layouts/navbar'
      .outer
        - flash.each do |key, msg|
          = content_tag :div, msg, :class => [key, " message"], :class => "alert alert-#{key}"
        = yield
          

        
    
      %footer
        %p &copy; Word Bird 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"}
    = javascript_include_tag "stats"
    = javascript_include_tag "game"